<?php

namespace Database\Seeders;

use App\Models\MPriceList;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class MPriceListDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Truncate table
        Schema::disableForeignKeyConstraints();
        DB::table('m_price_lists')->truncate();
        Schema::enableForeignKeyConstraints();

        $masterData = [
            [
                'service_type' => MPriceList::BEFORE_FILING,
                'package_type' => '1.1',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::BEFORE_FILING,
                'package_type' => '1.2',
                'base_price' => 2500,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::BEFORE_FILING,
                'package_type' => '1.3',
                'base_price' => 1500,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::BEFORE_FILING,
                'package_type' => '1.4',
                'base_price' => 10000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::BEFORE_FILING,
                'package_type' => '1.5',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::APPLICATION,
                'package_type' => '2.1',
                'base_price' => 2980,
                'pof_1st_distinction_5yrs' => 12000,
                'pof_1st_distinction_10yrs' => 12000,
                'pof_2nd_distinction_5yrs' => 8600,
                'pof_2nd_distinction_10yrs' => 8600,
            ],
            [
                'service_type' => MPriceList::APPLICATION,
                'package_type' => '2.2',
                'base_price' => 2000,
                'pof_1st_distinction_5yrs' => 12000,
                'pof_1st_distinction_10yrs' => 12000,
                'pof_2nd_distinction_5yrs' => 8600,
                'pof_2nd_distinction_10yrs' => 8600,
            ],
            [
                'service_type' => MPriceList::APPLICATION,
                'package_type' => '2.3',
                'base_price' => 10800,
                'pof_1st_distinction_5yrs' => 12000,
                'pof_1st_distinction_10yrs' => 12000,
                'pof_2nd_distinction_5yrs' => 8600,
                'pof_2nd_distinction_10yrs' => 8600,
            ],
            [
                'service_type' => MPriceList::APPLICATION,
                'package_type' => '2.4',
                'base_price' => 3000,
                'pof_1st_distinction_5yrs' => 12000,
                'pof_1st_distinction_10yrs' => 12000,
                'pof_2nd_distinction_5yrs' => 8600,
                'pof_2nd_distinction_10yrs' => 8600,
            ],
            [
                'service_type' => MPriceList::APPLICATION,
                'package_type' => '2.5',
                'base_price' => 19800,
                'pof_1st_distinction_5yrs' => 12000,
                'pof_1st_distinction_10yrs' => 12000,
                'pof_2nd_distinction_5yrs' => 8600,
                'pof_2nd_distinction_10yrs' => 8600,
            ],
            [
                'service_type' => MPriceList::APPLICATION,
                'package_type' => '2.6',
                'base_price' => 4000,
                'pof_1st_distinction_5yrs' => 12000,
                'pof_1st_distinction_10yrs' => 12000,
                'pof_2nd_distinction_5yrs' => 8600,
                'pof_2nd_distinction_10yrs' => 8600,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.1',
                'base_price' => 7000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.2',
                'base_price' => 2000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.3',
                'base_price' => 7000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.4',
                'base_price' => 1000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.5',
                'base_price' => 0,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.6',
                'base_price' => 1000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.7',
                'base_price' => 1500,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 8600,
                'pof_2nd_distinction_10yrs' => 8600,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.8',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 2100,
                'pof_1st_distinction_10yrs' => 2100,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.9',
                'base_price' => 3000,
                'pof_1st_distinction_5yrs' => 2100,
                'pof_1st_distinction_10yrs' => 2100,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.10',
                'base_price' => 10000,
                'pof_1st_distinction_5yrs' => 4200,
                'pof_1st_distinction_10yrs' => 4200,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REASONS_REFUSAL,
                'package_type' => '3.11',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REGISTRATION,
                'package_type' => '4.1',
                'base_price' => 10000,
                'pof_1st_distinction_5yrs' => 16400,
                'pof_1st_distinction_10yrs' => 32900,
                'pof_2nd_distinction_5yrs' => 17200,
                'pof_2nd_distinction_10yrs' => 32900,
            ],
            [
                'service_type' => MPriceList::REGISTRATION,
                'package_type' => '4.2',
                'base_price' => 3000,
                'pof_1st_distinction_5yrs' => 17200,
                'pof_1st_distinction_10yrs' => 32900,
                'pof_2nd_distinction_5yrs' => 17200,
                'pof_2nd_distinction_10yrs' => 32900,
            ],
            [
                'service_type' => MPriceList::REGISTRATION,
                'package_type' => '4.3',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REGISTRATION,
                'package_type' => '4.4',
                'base_price' => 3000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REGISTRATION,
                'package_type' => '4.5',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REGISTRATION,
                'package_type' => '4.6',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::REGISTRATION,
                'package_type' => '4.7',
                'base_price' => 3000,
                'pof_1st_distinction_5yrs' => 15700,
                'pof_1st_distinction_10yrs' => 15700,
                'pof_2nd_distinction_5yrs' => 15700,
                'pof_2nd_distinction_10yrs' => 15700,
            ],
            [
                'service_type' => MPriceList::REGISTRATION,
                'package_type' => '4.8',
                'base_price' => 0,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::LATE_PAYMENT_REGISTRATION,
                'package_type' => '5.1',
                'base_price' => 20000,
                'pof_1st_distinction_5yrs' => 17200,
                'pof_1st_distinction_10yrs' => 17200,
                'pof_2nd_distinction_5yrs' => 17200,
                'pof_2nd_distinction_10yrs' => 17200,
            ],
            [
                'service_type' => MPriceList::LATE_PAYMENT_REGISTRATION,
                'package_type' => '5.2',
                'base_price' => 2000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 17200,
                'pof_2nd_distinction_10yrs' => 17200,
            ],
            [
                'service_type' => MPriceList::EACH_PAYMENT,
                'package_type' => '6.1',
                'base_price' => 2000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::AT_REGISTRATION,
                'package_type' => '7.1',
                'base_price' => 3000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 0,
                'pof_2nd_distinction_10yrs' => 0,
            ],
            [
                'service_type' => MPriceList::UPDATE,
                'package_type' => '8.1',
                'base_price' => 20000,
                'pof_1st_distinction_5yrs' => 22800,
                'pof_1st_distinction_10yrs' => 43600,
                'pof_2nd_distinction_5yrs' => 22800,
                'pof_2nd_distinction_10yrs' => 43600,
            ],
            [
                'service_type' => MPriceList::UPDATE,
                'package_type' => '8.2',
                'base_price' => 2000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 22800,
                'pof_2nd_distinction_10yrs' => 43600,
            ],
            [
                'service_type' => MPriceList::LATE_PAYMENT_RENEWAL,
                'package_type' => '9.1',
                'base_price' => 20000,
                'pof_1st_distinction_5yrs' => 22800,
                'pof_1st_distinction_10yrs' => 22800,
                'pof_2nd_distinction_5yrs' => 22800,
                'pof_2nd_distinction_10yrs' => 22800,
            ],
            [
                'service_type' => MPriceList::LATE_PAYMENT_RENEWAL,
                'package_type' => '9.2',
                'base_price' => 2000,
                'pof_1st_distinction_5yrs' => 0,
                'pof_1st_distinction_10yrs' => 0,
                'pof_2nd_distinction_5yrs' => 22800,
                'pof_2nd_distinction_10yrs' => 22800,
            ],
            [
                'service_type' => MPriceList::CHANGE_PROCEDURE,
                'package_type' => '10.1',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 1000,
                'pof_1st_distinction_10yrs' => 1000,
                'pof_2nd_distinction_5yrs' => 1000,
                'pof_2nd_distinction_10yrs' => 1000,
            ],
            [
                'service_type' => MPriceList::CHANGE_PROCEDURE,
                'package_type' => '10.2',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 1000,
                'pof_1st_distinction_10yrs' => 1000,
                'pof_2nd_distinction_5yrs' => 1000,
                'pof_2nd_distinction_10yrs' => 1000,
            ],
            [
                'service_type' => MPriceList::FREE_HISTORY,
                'package_type' => '11.1',
                'base_price' => 5000,
                'pof_1st_distinction_5yrs' => 4600,
                'pof_1st_distinction_10yrs' => 4600,
                'pof_2nd_distinction_5yrs' => 4600,
                'pof_2nd_distinction_10yrs' => 4600,
            ],
            [
                'service_type' => MPriceList::OTHER,
                'package_type' => '12.1',
                'base_price' => 10000,
                'pof_1st_distinction_5yrs' => 4600,
                'pof_1st_distinction_10yrs' => 4600,
                'pof_2nd_distinction_5yrs' => 4600,
                'pof_2nd_distinction_10yrs' => 4600,
            ],
        ];
        MPriceList::insert($masterData);
    }
}
